Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

In [7]:
import numpy as np
def Vandermonde(arr,N):
    a = np.array(arr)
    o = np.column_stack([a**(N-k-1) for k in range(N)])
    print(o)
    
Vandermonde([2,4,6],3)

[[ 4  2  1]
 [16  4  1]
 [36  6  1]]


Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3

In [16]:
def moving_avg(lst, num):
    l = []
    for i,_ in enumerate(lst):
        a = i
        b = i+num
        if len(lst[a:b])<num:
            break
        l.append(lst[a:b])
        avg = [np.array(l[i]).mean() for i in range(len(l))]
    print(np.round_(avg,3))

moving_avg([1,4,6,7,9,13,19,25,34,49,53,66,82,96,98,100,108,126],3)

[  3.667   5.667   7.333   9.667  13.667  19.     26.     36.     45.333
  56.     67.     81.333  92.     98.    102.    111.333]
